### ISSUE TITLE
为何不使用ajax请求歌词？

### ISSUE THREAD

**Issue by cxgreat2014** [0936zz/mplayer#1]
硬编码很难看，而且很麻烦

**Comment by 0936zz** [comment]
谢谢反馈，后续版本会修改
您暂时可以使用ajax请求歌词然后将其赋值给变量

**Comment by cxgreat2014** [comment]
Thanks~!

**Comment by 0936zz** [comment]
ajax获取歌词已在最新版V2.1.0实现，详情查看[码云](http://git.oschina.net/0936zz/WMPlayer/)

**Comment by cxgreat2014** [comment]
厉害！谢谢
