### ISSUE TITLE
当音乐文件不存在404时 我怎么判断？

### ISSUE THREAD

**Issue by yangyl568** [0936zz/mplayer#6]
异步加载数据列表到页面数组，然后 下一曲或者开始播放时，发现 音频地址 不存在404，我如何捕捉到然后再去 提示用户？

**Comment by 0936zz** [comment]
暂时没有这个事件，v3版添加
或者可自行修改源码
此仓库已停止维护，v2版本最新在https://gitee.com/0936zz/WMPlayer
目前v2已经停止开发，v3未完成版在https://github.com/0936zz/wmplayer

**Comment by yangyl568** [comment]
自行修改源码的话，我应该从哪里下手？  可以给点提示吗？

**Comment by 0936zz** [comment]
https://github.com/0936zz/mplayer/blob/master/js/mplayer.js#L130
给audio添加error事件
