### ISSUE TITLE
我在使用的时候，加载歌单  很慢

### ISSUE THREAD

**Issue by yangyl568** [0936zz/mplayer#7]
比如 我有500首歌，甚至1000首歌。  加载的时候 很慢很慢  几乎要  50S才可以。
此时我应该怎么做？    楼主很急，在线等噢。    谢谢

QQ:  438933868

**Comment by 0936zz** [comment]
你是不是把歌词直接写进去了，解析歌词可能比较费时间
你可以试一下用ajax方式请求歌词

**Comment by yangyl568** [comment]
`没写歌词，` {"disabled": "prev" ,"name": "神霄煞仙001" , "singer": "蜘蛛","img": "/ProductImages/20161122111057.jpg","src": "/mp3/北京可以这样文化传媒/47神霄煞仙/sxsx001.mp3","title": "神霄煞仙","id":"152670"} `，
每条信息都是这样的。500条需要加载20+S，1000条需要 40+S，我分析了，好像是在 格式化的时候 卡了很久。

**Comment by yangyl568** [comment]
如果方便的话  QQ联系一下可好。   
还有个问题，尝试异步加载 歌单，但是 不知道 如何 异步的时候   初始化歌单。   所以才选择一次性加载 歌单，结果 发现卡了很久。

**Comment by 0936zz** [comment]
QQ群591646992

**Comment by yangyl568** [comment]
问题已经解决，使用的是   API里的 addsong函数。
